version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    command: bundle exec rails server -b 0.0.0.0
    entrypoint: "./entrypoints/docker-entrypoint.sh"
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: "true"
      
  database:
    image: postgres:12.3
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: 
      - .env

volumes:
  db_data:
  gem_cache:
  node_modules: