default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: stackoverflow_clone_development

test:
  <<: *default

production:
  <<: *default
  database: stackoverflow_clone_production
  # database: <%= ENV['DATABASE_NAME'] %>
  # username: <%= ENV['DATABASE_USER'] %>
  # password: <%= ENV['DATABASE_PASSWORD'] %>
  # port: <%= ENV['DATABASE_PORT'] || '5432' %>
  # host: <%= ENV['DATABASE_HOST'] %>
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # timeout: 5000

